### ISSUE TITLE
Kicad project not in root folder

### ISSUE THREAD

**Issue by leoheck** [INTI-CMNB/kicad_ci_test#1]
I am setting a project to use the info from here as a starting point.
Does this tool work if the Kicad project is inside a folder instead of the root path of the repo?

**Comment by set-soft** [comment]
Of course you can have the files in another folder. 
If you take a look at all the regression tests for the KiPlot and kicad-automation-scripts you'll see that the KiCad files are always in another folder.
You just need to specify the KiCad file and the YAML file using -b and -c command line options. 
KiPlot tries to be "smart" by guessing what you want, so another option is to change the current directory to where you files are located and run KiPlot there.
A more complex case is this project:
https://gitlab.com/set-soft/kicad-ci-test-spora/
Here 3 PCBs are included. The solution is quite clean, using makefiles to contain the commands.
