### ISSUE TITLE
ERC and DRC are being duplicated?

### ISSUE THREAD

**Issue by leoheck** [INTI-CMNB/kicad_ci_test#7]
Why do you use `-s run_drc,run_erc` and `-s all` explicitly in Kiblot command during _FabSch_ and _FabPCB_ steps if both have their `needs: ERC` and `needs: DRC` settings?

These checks are being duplicated. Do you think this is the best approach? Or maybe Kiplot command needs this on each step.

**Comment by set-soft** [comment]
The `-s run_drc,run_erc` means *skip DRC and ERC* and `-s all` means *skip all pre-flight options*.

In this example we have just one configuration file (kicad_ci_test.kiplot.yaml) this file contains all tests and outputs you want.  When using it locally you'll usually just run kiplot and all will be done at once. But here we are separating thing in 4 different jobs. So for each job we tell kiplot what to do. So when we want to do the ERC (and nothing more) we are using `kiplot  -d Fabrication -s update_xml,run_drc -i`, we skip DRC and XML update, and we don't generate any output. The default behavior is to generate all outputs, but `-i` is *invert the list of outputs* so we don't generate any output. This like is *just run the ERC*.
