### ISSUE TITLE
Is this ready?

### ISSUE THREAD

**Issue by hoijui** [INTI-CMNB/kicad_ci_test#8]
Hello Salvador! :-)
I wanted to try KiBot with the GitHub CI, and started by copying this script:
https://github.com/INTI-CMNB/kicad_ci_test/blob/master/.github/workflows/test1.yml

Tthen I saw, that it is calling `kiplot`, not `kibot`, and asked myself: is this already usable, or is it WIP, and I should wait some more?

**Comment by set-soft** [comment]
Currently kibot and kiplot commands are equivalent.
I'm slowly changing names to kibot, but is not important.
Most of the functionality is ready for production, covered by over than 300 regression tests. 
I'm trying to keep the API as compatible as possible. You can use *.kiplot.yaml or *kibot.yaml files, they should contain a section named kibot or kiplot, etc.

The "Variants" stuff isn't included in any release yet and is changing syntax details these days. The rest is compatible and will be changed only in v2.0.0, which is really far from now.
You can play with the workflows on this example:

https://github.com/INTI-CMNB/kicad-ci-test-spora

Is a three boards project.

**Comment by hoijui** [comment]
thank you for all that!
... wow.. this thing is phenomenal!
you know, I was looking for something... even much more modest then this all.. just for generating Gerbers, and I never got to KiBot (or even KiPlot)... this should be top on searches all the time!

I am working for OSEG around the new [DIN SPEC 3015](https://gitlab.com/OSEGermany/OHS), the first official standard for Open Source Hardware (which is also the first standard of the DIN that is open source its self). I ma looking for tools just like this.. this is really a gold-mine! it solves a lot of check-marks on my list, even some I had not on there!
Thanks to you, I'll be able to focus more on FreeCAD related tools for automation, which besides KiCad is our other main focus in this regard.

.. thanks a lot and.. ride on! :-)
very important stuff!

**Comment by set-soft** [comment]
Thanks!

The DIN SPEC 3015 is a really important idea. The "Open Hardware" term is used for very different stuff, having a spec is really good. And is really important that the spec is open, this is needed for this case and is a very positive thing.

**Comment by hoijui** [comment]
> El pueblo, unido, jamas era ...

;-)
